[project]
name = "llms-sustainability"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.55.0",
    "dotenv>=0.9.9",
    "openai>=1.92.2",
    "pandas>=2.3.0",
    "torch>=2.7.1",
    "transformers>=4.53.3",
]
